# Generated by Django 4.2.6 on 2023-10-10 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField()),
                ('ano', models.DateTimeField(auto_now_add=True)),
                ('pais', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeloFonografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Discos',
        ),
        migrations.AddField(
            model_name='disco',
            name='selo_fonografico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discos.selofonografico'),
        ),
        migrations.AddField(
            model_name='artista',
            name='discos',
            field=models.ManyToManyField(to='discos.disco'),
        ),
    ]
